### ISSUE TITLE
prompt for password

### ISSUE THREAD

**Issue by seanorama** [sequenceiq/ambari-shell#35]
Feature request: Prompting for password.

Passing a password with the command leaves it in your shell history which isn't great for security.

**Comment by lalyos** [comment]
Hi @seanorama, Yes you right, leaving passwords in shell history is no good. My workaround is to
set them in my `~/.profile` as env variables, as AMBARI_USER and AMBARI_PASSWORD.

**Comment by seanorama** [comment]
@lalyos I didn't realize ambari-shell checked the environment. I'll give it a try. Would it be worth catching a 'read' from the user if it's not set instead of assuming admin:admin?

**Comment by lalyos** [comment]
Sorry, I didn't meant that ambar-shell is checking the env vars. I wanted to suggest using:

```
  java -jar ambar-shell.jar --ambari.user=$AMBARI_USER --ambari.password=$AMBARI_PASSWORD
```

By speaking about it ... It might be usefull.

**Comment by lalyos** [comment]
The whole purpose of ambari-shell was: automation. So the main usecase is:
```
java -jar ambari-shell.jar --cmdfile=<FILE> : Ambari Shell executes commands read from the file.
```

Sure the cmdfile itself can be created, by starting an interactive ambari-shell, test the steps,
and finally clean up the saved history file.

But i'm a bit reluctant to add behaviour which waits for user interaction.
