### ISSUE TITLE
README lacks build instructions

### ISSUE THREAD

**Issue by ndimiduk** [sequenceiq/ambari-shell#46]
A little help for how to either build locally or get a release would go a long way...

**Comment by dp1140a** [comment]
+1
Please include some build instructions.  Do we use Gradle or Maven? I tried building the master branch and it failed on a dependency API issue with Ambari-client.  It does build on 1.6.0 and 1.7.0 branches but it wont run?

**Comment by keyki** [comment]
Yes, we should properly include the build instructions. 
```
./gradlew clean build
```
This project is part of the Apache Ambari that's why there is a pom.xml as well.
