### ISSUE TITLE
can't find ambari server

### ISSUE THREAD

**Issue by JSmith2412** [sequenceiq/ambari-shell#47]
So I've run through the guide, got up the `cluster build` command, and I get the following output:
`
 HOSTNAME  STATE
  --------  -----

  HOSTGROUP  COMPONENT
  ---------  -------------------
  master     HDFS_CLIENT
  master     ZOOKEEPER_CLIENT
  master     NAMENODE
  master     ZOOKEEPER_SERVER
  master     HISTORYSERVER
  master     APP_TIMELINE_SERVER
  master     RESOURCEMANAGER
  master     MAPREDUCE2_CLIENT
  master     SECONDARY_NAMENODE
  master     NODEMANAGER
  master     TEZ_CLIENT
  master     DATANODE
  master     YARN_CLIENT
`
so when I run `cluster assign`, it says my hostname is not valid.

**Comment by mhmxs** [comment]
Hi @JSmith2412,

Sorry for the late answer, i hope it isn't an issue for you any more, otherwise let me know.
